---
# ALL UNITS ARE IN AGENT BODY LENGTHS UNLESS OTHERWISE SPECIFIED
type: "RectangularWorld"
size:  # Defined in Agent Body Lengths
  - 100
  - 100
n_agents: 20
init_type:
  type: "RectRandomInit"  # A starting region where agents will spawn at t=0
  bb:
    - - 46 # Upper Left Bounding Box Corner (Body Lengths) X
      - 46 # Y
    - - 54 # Lower Right Bounding Box Corner (Body Lengths) X
      - 54 # Y
  seed: 2023 # ADD SEED HERE TO ENSURE SAME INITIALIZATION EVERY TIME
padding: 0
collide_walls: false  # Use No Environment Walls for this problem
show_walls: false  # Hide Default Walls,
metadata:
  hash: _hash
stop_at: 1000000 # Upper Simulation Limit (timesteps)